# Generated by Django 4.2.6 on 2024-02-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_rating_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='createdAt',
        ),
    ]
